version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: Docs/source/conf.py

python:
  install:
    - requirements: Docs/source/requirements.txt
    - requirements: Docs/source/requirements2.txt
    - method: pip
      path: .
      extra_requirements:
        - docs