version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: Docs/source/conf.py


# Optionally set the version of Python and requirements required to build your docs
python:
  version: 3.11
  install:
      - requirements: Docs/source/requirements.txt
      - requirements: Docs/source/requirements2.txt
      - method: pip
        path: .

